//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""GamepadControls"",
            ""id"": ""69757c57-bf74-4d25-af12-a9a51fdf2e73"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d456be5a-01cc-4b5f-a17f-3383e0894978"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Running"",
                    ""type"": ""Button"",
                    ""id"": ""afc8b41a-dc56-4086-b11f-4bfe3ce8d165"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""675d0d30-18f5-4776-84b5-cd0c53fba00e"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Running"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""013cbc1e-2573-431f-9e7f-dbf2bb3c058b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamepadControls
        m_GamepadControls = asset.FindActionMap("GamepadControls", throwIfNotFound: true);
        m_GamepadControls_Movement = m_GamepadControls.FindAction("Movement", throwIfNotFound: true);
        m_GamepadControls_Running = m_GamepadControls.FindAction("Running", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamepadControls
    private readonly InputActionMap m_GamepadControls;
    private List<IGamepadControlsActions> m_GamepadControlsActionsCallbackInterfaces = new List<IGamepadControlsActions>();
    private readonly InputAction m_GamepadControls_Movement;
    private readonly InputAction m_GamepadControls_Running;
    public struct GamepadControlsActions
    {
        private @PlayerInput m_Wrapper;
        public GamepadControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_GamepadControls_Movement;
        public InputAction @Running => m_Wrapper.m_GamepadControls_Running;
        public InputActionMap Get() { return m_Wrapper.m_GamepadControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamepadControlsActions set) { return set.Get(); }
        public void AddCallbacks(IGamepadControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_GamepadControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamepadControlsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Running.started += instance.OnRunning;
            @Running.performed += instance.OnRunning;
            @Running.canceled += instance.OnRunning;
        }

        private void UnregisterCallbacks(IGamepadControlsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Running.started -= instance.OnRunning;
            @Running.performed -= instance.OnRunning;
            @Running.canceled -= instance.OnRunning;
        }

        public void RemoveCallbacks(IGamepadControlsActions instance)
        {
            if (m_Wrapper.m_GamepadControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamepadControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_GamepadControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamepadControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamepadControlsActions @GamepadControls => new GamepadControlsActions(this);
    public interface IGamepadControlsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRunning(InputAction.CallbackContext context);
    }
}
